### ISSUE TITLE
notracking list has not updated for 20 days

### ISSUE THREAD

**Issue by chr-lei** [nextdns/blocklists#101]
The notracking blocklist has not updated for 20 days, but the source list is being updated regularly.

Just searched and it looks like this is related to #93  and possibly fixed by #98 but I did not see an issue open for it. @romaincointepas  could you look at @GiddyGoatGaming 's proposed fix in #98 and merge if appropriate?

**Comment by romaincointepas** [comment]
Fixed in https://github.com/nextdns/blocklists/commit/b62bde75761486118286bbd3c3dbadc30d325cca.
