### ISSUE TITLE
My Denylist Not Being Obeyed

### ISSUE THREAD

**Issue by rjm831** [nextdns/blocklists#118]
Have an entry in my Deny list:  alt-android-billing-api.cloud.mail.ru.  Despite being in the Deny list it continues to connect {the connections show up in the log}.  Don't understand this; perhaps it is not a NextDNS issue but somehow the app involved (my Mail.ru cloud storage app) is somehow bypassing the Deny  list?

**Comment by quantumpacket** [comment]
Is the log entry being marked red? Have you explicitly allowed `cloud.mail.ru` or `mail.ru` in your Allowlist? Allowlist rules take precedence over Denylist rules.

**Comment by rjm831** [comment]
No it wasn't marked red, but I do in fact have three mail.ru entries listed in my Allow list so I think you've solved the issue for me.  Didn't realize Allow is precedence.  Thank you for the help!
