### ISSUE TITLE
Add Homograph / homoglyph protection

### ISSUE THREAD

**Issue by mrx23dot** [nextdns/blocklists#151]
Add option to block domains with Homograph / homoglyph (e.g. greek ) symbols.
Most people only use ascii domains.

it would protect against phising emails
https://en.wikipedia.org/wiki/IDN_homograph_attack
https://www.bitdefender.com/blog/businessinsights/homograph-phishing-attacks-when-user-awareness-is-not-enough/

**Comment by cbuijs** [comment]
Is already a feature (for a while)?

Under the "Security" tab, and then the 7th block called "IDN Homograph Attacks Protection"?
