### ISSUE TITLE
Please, add HaGeZi's Encrypted DNS/VPN/TOR/Proxy Bypass DNS Blocklist

### ISSUE THREAD

**Issue by catfluoride** [nextdns/blocklists#152]
The repository at https://github.com/nextdns/dns-bypass-methods is severely outdated (last update 1 year and half ago, as of now).

Please, consider adding HaGeZi's Encrypted DNS/VPN/TOR/Proxy Bypass DNS Blocklist to nextdns block lists:

https://github.com/hagezi/dns-blocklists/blob/main/wildcard/doh-vpn-proxy-bypass-onlydomains.txt

which is update consistently, on hourly or daily base. 

Lists that haven't been updated in years are hardly useful.

Thanks a lot in advance.

**Comment by vdias** [comment]
Any update on this request?

**Comment by romaincointepas** [comment]
Added, thanks

**Comment by vdias** [comment]
Cannot see it as a list? Did you guys just added the hazegi list to your "Threat Intelligence Feed" as a new source?

**Comment by romaincointepas** [comment]
It was added internally as one of the sources for Block Bypass Methods.

**Comment by vdias** [comment]
Cannot see any changes on github... kinda weird...
