### ISSUE TITLE
oisd list not uptodate

### ISSUE THREAD

**Issue by ijuliank** [nextdns/blocklists#73]
title

**Comment by sjhgvr** [comment]
But being updated again.

**Comment by romaincointepas** [comment]
@sjhgvr there seems to be a bug with the handling of conditional requests on your side:

When sending `if-none-match: "8a587623"` to `https://dblw.oisd.nl`, you are responding with a `304`, but with `etag: "88c35505"`. That's why the list is not updating.

Could you take a look?

**Comment by sjhgvr** [comment]
> @sjhgvr there seems to be a bug with the handling of conditional requests on your side:
> 
> When sending `if-none-match: "8a587623"` to `https://dblw.oisd.nl`, you are responding with a `304`, but with `etag: "88c35505"`. That's why the list is not updating.
> 
> Could you take a look?

As far as I can tell that's not it?

$ curl -I --header "If-None-Match: \"8a587623\"" https://dblw.oisd.nl
HTTP/2 200
strict-transport-security: max-age=63072000; includeSubDomains; preload
referrer-policy: strict-origin-when-cross-origin
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-permitted-cross-domain-policies: master-only
content-security-policy: frame-ancestors oisd.nl *.oisd.nl
etag: "3da4972c"
content-type: text/html; charset=utf-8
date: Thu, 15 Dec 2022 02:37:40 GMT
server: Apache

$ curl -I --header "If-None-Match: \"3da4972c\"" https://dblw.oisd.nl
HTTP/2 304
strict-transport-security: max-age=63072000; includeSubDomains; preload
referrer-policy: strict-origin-when-cross-origin
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-permitted-cross-domain-policies: master-only
content-security-policy: frame-ancestors oisd.nl *.oisd.nl
etag: "3da4972c"
date: Thu, 15 Dec 2022 02:37:54 GMT
server: Apache

**Comment by sjhgvr** [comment]
Seems to be working again. Did you by any chance also send a "If-Modified-Since" -header?
I've now removed that. Maybe it was that giving an issue.

**Comment by romaincointepas** [comment]
@sjhgvr yep that was it thanks, the issue was with the handling of `last-modified`/`if-modified-since` it seems.
