### ISSUE TITLE
Please Add OISD Full and OISD NSFW

### ISSUE THREAD

**Issue by jmcglock** [nextdns/blocklists#83]
Please add these two blocklists:
OISD Full: https://dbl.oisd.nl/
OISD NSFW: https://dbl.oisd.nl/nsfw/

**Comment by travisboss** [comment]
OISD Full is already added to this project.

There Porn lists (what NSFW would fall under) went internal recently to use there AI it looks like.

**Comment by jmcglock** [comment]
Thanks so much for responding. I was unsure if the OISD blocklist already used was the "Full" list. 

I will close this issue since there is no changes to be made.

Cheers.
