### ISSUE TITLE
Remove Dead Blocklists

### ISSUE THREAD

**Issue by jmcglock** [nextdns/blocklists#84]
The following blocklists are dead (they show 0 entries in NextDNS) and should either be updated or removed:
Energized Spark
Energized Ultimate
Energized Xtreme Extension
Energized Blu
Energized Basic

<img width="448" alt="image" src="https://user-images.githubusercontent.com/85720969/213271115-92f95f6e-1faf-4aed-8f1a-6dfb1ce9215a.png">

Thanks

**Comment by devipasigner** [comment]
Since you added the Hagezi lists, I agree that the energized lists should be removed. Maintainer is inactive and lists are full of false positives.

**Comment by jmcglock** [comment]
Stale
