### ISSUE TITLE
Discord Updates are Blocked

### ISSUE THREAD

**Issue by jmcglock** [nextdns/blocklists#91]
Looks like NextDNS "piracy" blocklist is blocking updates for Discord.

![image](https://user-images.githubusercontent.com/85720969/213743120-404e9b18-4ad1-4ea9-8518-585edf0b4977.png)

**Comment by GiddyGoatGaming** [comment]
Was your issue fixed after https://github.com/nextdns/piracy-blocklists/commit/41d014a76cda410de2e4c207601f59767dc6285a

**Comment by jmcglock** [comment]
Issue fixed. Thank you.
