### ISSUE TITLE
OISD Basic blocklist

### ISSUE THREAD

**Issue by hlqviet** [nextdns/blocklists#94]
Can you please consider adding the OISD Basic blocklist? It is the best blocklist for people like me who just want to block only ads. I wouldn't be able to achieve the same goal even if I add the current ad blocklists in NextDNS.

**Comment by romaincointepas** [comment]
Is there a reason why you would want to only use basic instead of full?

https://oisd.nl/faq#basic

**Comment by hlqviet** [comment]
It isn't about size limitation but the target of the list.

The full list block ads and also other things such as trackers and analytics while the basic list focuses mainly on ads (included lists [here](https://oisd.nl/includedlists)). In some use cases I need the trackers and analytics but it would require too much work to allow one by one.

**Comment by romaincointepas** [comment]
@sjhgvr what's your take on this?

**Comment by sjhgvr** [comment]
> @sjhgvr what's your take on this?

Could be a valid reason to add oisd basic as well.
While you're at it, you might want to add oisd nsfw (big) as well.

**Comment by hlqviet** [comment]
Hi. Is there anything else that prevents it from being added?

**Comment by hlqviet** [comment]
Hi @romaincointepas, is it gonna be added?

**Comment by mintss-zez0** [comment]
Hi @romaincointepas, can you take a look at this PR [https://github.com/nextdns/blocklists/pull/111](url)

**Comment by hlqviet** [comment]
No progress
